//! Every civilization's city names, moved out of the engine.
//!
//! ⚠⚠ THE COMMIT THAT CLAIMED TO DO THIS DID NOT. #1846 is titled "game.rs:
//! move the interleaved test modules **and the city-name tables** out", and it
//! moved `city_name_tests.rs` — the tests — while these 1,895 lines stayed
//! exactly where they were at `src/game.rs:397`. Its body listed `city_names`
//! as remaining work, so anyone reading the body was fine and anyone reading
//! the log was told the opposite. The title is the part that gets read.
//!
//! This is content, not logic: no rules, no branches, one lookup. Sitting in
//! the middle of the engine's hottest Rust file it added a conflict surface to
//! every edit near the top of that file, which at a hundred merged pull
//! requests a day is a cost paid by other people.
//!
//! A verbatim move — same bytes, same order — with only the `fn` line gaining
//! `pub(super)` so `game` can still call it.

pub(super) fn city_names(civ: &str) -> &'static [&'static str] {
    match civ {
        "Rome" => &[
            "Rome",
            "Ostia",
            "Antium",
            "Ravenna",
            "Cumae",
            "Aquileia",
            "Puteoli",
            "Arretium",
            "Brundisium",
            "Caesarea",
            "Massilia",
            "Neapolis",
            "Verona",
            "Placentia",
            "Augusta Treverorum",
            "Camulodunum",
        ],
        "Egypt" => &[
            "Thebes",
            "Memphis",
            "Akhetaten",
            "Giza",
            "Alexandria",
            "Pi-Ramesses",
            "Heliopolis",
            "Elephantine",
            "Abydos",
            "Edfu",
            "Amarna",
            "Saqqara",
            "Tanis",
            "Hierakonpolis",
            "Pelusium",
            "Canopus",
        ],
        "Greece" => &[
            "Athens",
            "Sparta",
            "Corinth",
            "Argos",
            "Delphi",
            "Olympia",
            "Knossos",
            "Mycenae",
            "Thebes",
            "Larissa",
            "Epidaurus",
            "Miletus",
            "Rhodes",
            "Syracuse",
            "Ephesus",
            "Halicarnassus",
        ],
        "China" => &[
            "Xian",
            "Chengdu",
            "Luoyang",
            "Kaifeng",
            "Beijing",
            "Nanjing",
            "Hangzhou",
            "Guangzhou",
            "Wuhan",
            "Changsha",
            "Anyang",
            "Lanzhou",
            "Suzhou",
            "Xiamen",
            "Jinan",
            "Datong",
        ],
        "Sumeria" => &[
            "Uruk",
            "Ur",
            "Nippur",
            "Lagash",
            "Eridu",
            "Kish",
            "Umma",
            "Shuruppak",
            "Adab",
            "Larsa",
            "Isin",
            "Girsu",
            "Bad-tibira",
            "Sippar",
            "Eshnunna",
            "Akshak",
        ],
        "Aztec" => &[
            "Tenochtitlan",
            "Texcoco",
            "Tlatelolco",
            "Xochimilco",
            "Tlacopan",
            "Azcapotzalco",
            "Chalco",
            "Culhuacan",
            "Tepotzotlan",
            "Tula",
            "Malinalco",
            "Cuauhnahuac",
            "Huaxtepec",
            "Teotihuacan",
            "Tenayuca",
            "Coatepec",
        ],
        "Nubia" => &[
            "Meroe",
            "Kerma",
            "Napata",
            "Dongola",
            "Kawa",
            "Naqa",
            "Musawwarat",
            "Soleb",
            "Amara",
            "Semna",
            "Buhen",
            "Qasr Ibrim",
            "Faras",
            "Sai",
            "Gebel Barkal",
            "El-Kurru",
        ],
        "Scythia" => &[
            "Pokrovka",
            "Gelonos",
            "Kamenka",
            "Aktau",
            "Neapolis",
            "Panticapaeum",
            "Chertomlyk",
            "Solokha",
            "Arzhan",
            "Pazyryk",
            "Belsk",
            "Auliekol",
            "Tillia Tepe",
            "Issyk",
            "Alexandropol",
            "Olbia",
        ],
        "England" => &[
            "London",
            "Liverpool",
            "Manchester",
            "Birmingham",
            "Leeds",
            "York",
            "Bristol",
            "Newcastle",
            "Coventry",
            "Sheffield",
            "Nottingham",
            "Portsmouth",
            "Oxford",
            "Cambridge",
            "Canterbury",
            "Plymouth",
        ],
        "Germany" => &[
            "Aachen",
            "Cologne",
            "Frankfurt",
            "Munich",
            "Hamburg",
            "Nuremberg",
            "Mainz",
            "Berlin",
            "Leipzig",
            "Dresden",
            "Bremen",
            "Augsburg",
            "Heidelberg",
            "Trier",
            "Regensburg",
            "Stuttgart",
        ],
        "Russia" => &[
            "Moscow",
            "St Petersburg",
            "Novgorod",
            "Kazan",
            "Rostov",
            "Yekaterinburg",
            "Nizhny Novgorod",
            "Smolensk",
            "Tver",
            "Vladimir",
            "Yaroslavl",
            "Voronezh",
            "Samara",
            "Tula",
            "Pskov",
            "Astrakhan",
        ],
        "Korea" => &[
            "Gyeongju",
            "Hanseong",
            "Pyongyang",
            "Kaesong",
            "Sangju",
            "Jeonju",
            "Gongju",
            "Buyeo",
            "Naju",
            "Chuncheon",
            "Wonju",
            "Ganghwa",
            "Suwon",
            "Andong",
            "Jinju",
            "Cheongju",
        ],
        "Maya" => &[
            "Palenque",
            "Tikal",
            "Copan",
            "Calakmul",
            "Chichen Itza",
            "Uxmal",
            "Yaxchilan",
            "Caracol",
            "Coba",
            "Bonampak",
            "Quirigua",
            "Naranjo",
            "Piedras Negras",
            "Tulum",
            "Mayapan",
            "Dos Pilas",
        ],
        "Mali" => &[
            "Niani",
            "Timbuktu",
            "Djenne",
            "Gao",
            "Walata",
            "Kumbi Saleh",
            "Segou",
            "Bamako",
            "Kangaba",
            "Taghaza",
            "Tadmekka",
            "Awdaghost",
            "Sikasso",
            "Nioro",
            "Kayes",
            "Mopti",
        ],
        "Phoenicia" => &[
            "Tyre",
            "Sidon",
            "Byblos",
            "Berytus",
            "Arwad",
            "Ugarit",
            "Sarepta",
            "Tripolis",
            "Utica",
            "Gadir",
            "Motya",
            "Panormus",
            "Lixus",
            "Hadrumetum",
            "Kition",
            "Tharros",
        ],
        "Byzantium" => &[
            "Constantinople",
            "Nicaea",
            "Thessalonica",
            "Antioch",
            "Trebizond",
            "Adrianople",
            "Smyrna",
            "Dyrrachium",
            "Iconium",
            "Chalcedon",
            "Sardica",
            "Varna",
            "Cherson",
            "Nicomedia",
            "Ancyra",
            "Amorium",
        ],
        "Zulu" => &[
            "Ulundi",
            "Nobamba",
            "Mgungundlovu",
            "Bulawayo",
            "Ondini",
            "Nodwengu",
            "Emakhosini",
            "Gibixhegu",
            "KwaDukuza",
            "Eshowe",
            "Empangeni",
            "Nongoma",
            "Mahlabathini",
            "Melmoth",
            "Vryheid",
            "Ingwavuma",
        ],
        "Gaul" => &[
            "Bibracte",
            "Cenabum",
            "Gergovia",
            "Alesia",
            "Lutetia",
            "Avaricum",
            "Narbo",
            "Tolosa",
            "Burdigala",
            "Lugdunum",
            "Nemausus",
            "Vesontio",
            "Agedincum",
            "Noviodunum",
            "Durocortorum",
            "Samarobriva",
        ],
        "Kongo" => &[
            "Mbanza-Kongo",
            "Mbanza Mbata",
            "Mbanza Soyo",
            "Mbanza Nsundi",
            "Mbanza Mpangu",
            "Mbanza Mbamba",
            "Nkusu",
            "Mpemba",
            "Luanda",
            "Matadi",
            "Boma",
            "Kabinda",
            "Mindouli",
            "Loango",
            "Nsanda",
            "Kinkanga",
        ],
        "Vietnam" => &[
            "Hanoi",
            "Hue",
            "Saigon",
            "Da Nang",
            "Hai Phong",
            "Co Loa",
            "Vinh",
            "Can Tho",
            "Nha Trang",
            "Quy Nhon",
            "Bien Hoa",
            "Nam Dinh",
            "Thanh Hoa",
            "Lang Son",
            "Cao Bang",
            "My Tho",
        ],
        "Brazil" => &[
            "Rio de Janeiro",
            "Sao Paulo",
            "Salvador",
            "Recife",
            "Brasilia",
            "Belo Horizonte",
            "Fortaleza",
            "Manaus",
            "Porto Alegre",
            "Curitiba",
            "Belem",
            "Natal",
            "Sao Luis",
            "Olinda",
            "Ouro Preto",
            "Santos",
        ],
        "France" => &[
            "Paris",
            "Orleans",
            "Lyon",
            "Reims",
            "Tours",
            "Bordeaux",
            "Rouen",
            "Dijon",
            "Toulouse",
            "Poitiers",
            "Nantes",
            "Amiens",
            "Grenoble",
            "Limoges",
            "Angers",
            "Besancon",
        ],
        "Spain" => &[
            "Madrid",
            "Toledo",
            "Sevilla",
            "Valladolid",
            "Zaragoza",
            "Cordoba",
            "Salamanca",
            "Burgos",
            "Granada",
            "Segovia",
            "Leon",
            "Avila",
            "Cuenca",
            "Merida",
            "Caceres",
            "Soria",
        ],
        "Portugal" => &[
            "Lisboa",
            "Porto",
            "Coimbra",
            "Braga",
            "Evora",
            "Guimaraes",
            "Viseu",
            "Leiria",
            "Santarem",
            "Faro",
            "Beja",
            "Lamego",
            "Guarda",
            "Portalegre",
            "Tomar",
            "Braganca",
        ],
        "Netherlands" => &[
            "Den Haag",
            "Rotterdam",
            "Utrecht",
            "Haarlem",
            "Leiden",
            "Delft",
            "Groningen",
            "Nijmegen",
            "Arnhem",
            "Maastricht",
            "Breda",
            "Eindhoven",
            "Zwolle",
            "Deventer",
            "Alkmaar",
            "Dordrecht",
        ],
        "Sweden" => &[
            "Uppsala",
            "Sigtuna",
            "Linkoping",
            "Orebro",
            "Vasteras",
            "Norrkoping",
            "Jonkoping",
            "Kalmar",
            "Skara",
            "Nykoping",
            "Falun",
            "Gavle",
            "Karlstad",
            "Vaxjo",
            "Umea",
            "Lund",
        ],
        "Norway" => &[
            "Nidaros",
            "Bergen",
            "Oslo",
            "Tonsberg",
            "Stavanger",
            "Hamar",
            "Skien",
            "Lillehammer",
            "Molde",
            "Bodo",
            "Alta",
            "Voss",
            "Roros",
            "Kongsberg",
            "Halden",
            "Narvik",
        ],
        "Denmark" => &[
            "Roskilde",
            "Aarhus",
            "Odense",
            "Aalborg",
            "Ribe",
            "Viborg",
            "Randers",
            "Horsens",
            "Kolding",
            "Vejle",
            "Silkeborg",
            "Herning",
            "Holstebro",
            "Skive",
            "Naestved",
            "Slagelse",
        ],
        "Poland" => &[
            "Krakow",
            "Warszawa",
            "Gniezno",
            "Poznan",
            "Wroclaw",
            "Lublin",
            "Torun",
            "Plock",
            "Sandomierz",
            "Kalisz",
            "Lodz",
            "Radom",
            "Kielce",
            "Opole",
            "Legnica",
            "Przemysl",
        ],
        "Hungary" => &[
            "Buda",
            "Esztergom",
            "Szekesfehervar",
            "Debrecen",
            "Szeged",
            "Pecs",
            "Gyor",
            "Eger",
            "Miskolc",
            "Veszprem",
            "Sopron",
            "Kecskemet",
            "Szolnok",
            "Vac",
            "Kalocsa",
            "Tokaj",
        ],
        "Austria" => &[
            "Wien",
            "Salzburg",
            "Graz",
            "Linz",
            "Innsbruck",
            "Klagenfurt",
            "Melk",
            "Krems",
            "Villach",
            "Wels",
            "Steyr",
            "Bregenz",
            "Sankt Polten",
            "Baden",
            "Leoben",
            "Amstetten",
        ],
        "Bohemia" => &[
            "Praha",
            "Brno",
            "Kutna Hora",
            "Plzen",
            "Olomouc",
            "Ceske Budejovice",
            "Hradec Kralove",
            "Cheb",
            "Tabor",
            "Jihlava",
            "Znojmo",
            "Pardubice",
            "Liberec",
            "Trebic",
            "Kolin",
            "Melnik",
        ],
        "Scotland" => &[
            "Edinburgh",
            "Stirling",
            "Perth",
            "Glasgow",
            "Aberdeen",
            "Dundee",
            "Inverness",
            "Dunfermline",
            "Scone",
            "Elgin",
            "Ayr",
            "Falkirk",
            "Dumfries",
            "Paisley",
            "Kirkcaldy",
            "Oban",
        ],
        "Ireland" => &[
            "Dublin",
            "Tara",
            "Cashel",
            "Armagh",
            "Cork",
            "Limerick",
            "Galway",
            "Kildare",
            "Clonmacnoise",
            "Waterford",
            "Kilkenny",
            "Sligo",
            "Wexford",
            "Ennis",
            "Trim",
            "Kells",
        ],
        "Switzerland" => &[
            "Bern",
            "Zurich",
            "Basel",
            "Geneve",
            "Luzern",
            "Lausanne",
            "Sankt Gallen",
            "Chur",
            "Winterthur",
            "Schaffhausen",
            "Fribourg",
            "Neuchatel",
            "Sion",
            "Zug",
            "Solothurn",
            "Aarau",
        ],
        "Venice" => &[
            "Venezia",
            "Padova",
            "Pordenone",
            "Vicenza",
            "Treviso",
            "Brescia",
            "Bergamo",
            "Udine",
            "Rovigo",
            "Belluno",
            "Chioggia",
            "Feltre",
            "Bassano",
            "Conegliano",
            "Adria",
            "Este",
        ],
        "Serbia" => &[
            "Beograd",
            "Skopje",
            "Nis",
            "Prizren",
            "Novi Sad",
            "Kragujevac",
            "Krusevac",
            "Smederevo",
            "Subotica",
            "Zrenjanin",
            "Cacak",
            "Sabac",
            "Valjevo",
            "Uzice",
            "Pirot",
            "Vranje",
        ],
        "Bulgaria" => &[
            "Pliska",
            "Tarnovo",
            "Sofia",
            "Plovdiv",
            "Vidin",
            "Ruse",
            "Shumen",
            "Sliven",
            "Stara Zagora",
            "Pleven",
            "Dobrich",
            "Pernik",
            "Haskovo",
            "Yambol",
            "Lovech",
            "Silistra",
        ],
        "Lithuania" => &[
            "Kernave",
            "Trakai",
            "Kaunas",
            "Siauliai",
            "Panevezys",
            "Klaipeda",
            "Alytus",
            "Marijampole",
            "Utena",
            "Telsiai",
            "Taurage",
            "Mazeikiai",
            "Jonava",
            "Kedainiai",
            "Ukmerge",
            "Raseiniai",
        ],
        "Ukraine" => &[
            "Kyiv",
            "Chernihiv",
            "Poltava",
            "Lviv",
            "Vinnytsia",
            "Zhytomyr",
            "Cherkasy",
            "Uman",
            "Kaniv",
            "Bila Tserkva",
            "Kropyvnytskyi",
            "Sumy",
            "Kharkiv",
            "Rivne",
            "Lutsk",
            "Ternopil",
        ],
        "Finland" => &[
            "Turku",
            "Helsinki",
            "Tampere",
            "Hameenlinna",
            "Porvoo",
            "Vaasa",
            "Oulu",
            "Kuopio",
            "Jyvaskyla",
            "Lahti",
            "Joensuu",
            "Mikkeli",
            "Rovaniemi",
            "Kotka",
            "Pori",
            "Savonlinna",
        ],
        "Romania" => &[
            "Targoviste",
            "Bucuresti",
            "Sibiu",
            "Brasov",
            "Cluj",
            "Iasi",
            "Timisoara",
            "Craiova",
            "Suceava",
            "Alba Iulia",
            "Arad",
            "Oradea",
            "Ploiesti",
            "Pitesti",
            "Bacau",
            "Galati",
        ],
        "Novgorod" => &[
            "Holmgard",
            "Ladoga",
            "Izborsk",
            "Torzhok",
            "Rusa",
            "Beloozero",
            "Vologda",
            "Ustyug",
            "Vyatka",
            "Kholmogory",
            "Onega",
            "Kargopol",
            "Toropets",
            "Velikiye Luki",
            "Staraya Russa",
            "Demyansk",
        ],
        "Prussia" => &[
            "Konigsberg",
            "Potsdam",
            "Stettin",
            "Magdeburg",
            "Halle",
            "Breslau",
            "Danzig",
            "Elbing",
            "Frankfurt an der Oder",
            "Brandenburg",
            "Kolberg",
            "Thorn",
            "Marienburg",
            "Kustrin",
            "Glogau",
            "Schwerin",
        ],
        "Catalonia" => &[
            "Barcelona",
            "Girona",
            "Lleida",
            "Tarragona",
            "Vic",
            "Manresa",
            "Tortosa",
            "Reus",
            "Sabadell",
            "Terrassa",
            "Mataro",
            "Igualada",
            "Olot",
            "Berga",
            "Solsona",
            "Balaguer",
        ],
        "Gujarat" => &[
            "Anhilwara",
            "Lothal",
            "Dholavira",
            "Khambhat",
            "Junagadh",
            "Bharuch",
            "Surat",
            "Vadodara",
            "Dwarka",
            "Somnath",
            "Idar",
            "Modhera",
            "Siddhpur",
            "Palitana",
            "Champaner",
            "Veraval",
        ],
        "Assyria" => &[
            "Assur",
            "Nineveh",
            "Nimrud",
            "Dur-Sharrukin",
            "Arbela",
            "Harran",
            "Kalhu",
            "Guzana",
            "Imgur-Enlil",
            "Shibaniba",
            "Tarbisu",
            "Kar-Tukulti",
            "Ekallatum",
            "Shubat-Enlil",
            "Til Barsip",
            "Carchemish",
        ],
        "Persia" => &[
            "Persepolis",
            "Pasargadae",
            "Susa",
            "Ecbatana",
            "Anshan",
            "Istakhr",
            "Bishapur",
            "Rey",
            "Nishapur",
            "Yazd",
            "Kerman",
            "Qom",
            "Kashan",
            "Hamadan",
            "Shiraz",
            "Zaranj",
        ],
        "Media" => &[
            "Hagmatana",
            "Rhagae",
            "Aspadana",
            "Laodicea",
            "Bagistana",
            "Kunaxa",
            "Nisaya",
            "Kampanda",
            "Sagbita",
            "Karkashi",
            "Zakruti",
            "Uppuria",
            "Bit-Kari",
            "Andirpatianu",
            "Sikris",
            "Uriakku",
        ],
        "Manchuria" => &[
            "Hetu Ala",
            "Mukden",
            "Jilin",
            "Ningguta",
            "Aigun",
            "Qiqihar",
            "Yarkand",
            "Hulun",
            "Sanxing",
            "Fuzhou",
            "Liaoyang",
            "Kaiyuan",
            "Tieling",
            "Yingkou",
            "Dandong",
            "Hunchun",
        ],
        "Lydia" => &[
            "Sardis",
            "Kaystros",
            "Torrhebos",
            "Magnesia",
            "Attaleia",
            "Thyateira",
            "Hypaepa",
            "Tralles",
            "Hierapolis",
            "Silandos",
            "Colossae",
            "Aphrodisias",
            "Priene",
            "Dioshieron",
            "Mylasa",
            "Alabanda",
        ],
        "Parthia" => &[
            "Nisa",
            "Ctesiphon",
            "Hecatompylos",
            "Merv",
            "Arsak",
            "Asaak",
            "Dara",
            "Charax",
            "Seleucia",
            "Vologesocerta",
            "Apamea",
            "Europos",
            "Arsakia",
            "Gabae",
            "Zadracarta",
            "Kangavar",
        ],
        "Sogdiana" => &[
            "Samarkand",
            "Bukhara",
            "Panjikent",
            "Kesh",
            "Nasaf",
            "Ustrushana",
            "Chach",
            "Khujand",
            "Termez",
            "Varakhsha",
            "Paykend",
            "Dabusiya",
            "Ishtikhan",
            "Kushaniya",
            "Maymurgh",
            "Rivdad",
        ],
        "Ottomans" => &[
            "Istanbul",
            "Bursa",
            "Edirne",
            "Konya",
            "Ankara",
            "Izmir",
            "Trabzon",
            "Sivas",
            "Kayseri",
            "Diyarbakir",
            "Antalya",
            "Amasya",
            "Manisa",
            "Erzurum",
            "Van",
            "Urfa",
        ],
        "Arabia" => &[
            "Baghdad",
            "Damascus",
            "Mecca",
            "Medina",
            "Kufa",
            "Basra",
            "Aleppo",
            "Riyadh",
            "Najran",
            "Taif",
            "Hail",
            "Buraydah",
            "Tabuk",
            "Yanbu",
            "Khaybar",
            "Jeddah",
        ],
        "Israel" => &[
            "Hebron",
            "Shechem",
            "Beersheba",
            "Megiddo",
            "Lachish",
            "Jericho",
            "Bethel",
            "Shiloh",
            "Gezer",
            "Hazor",
            "Beth Horon",
            "Gibeon",
            "Ramah",
            "Mizpah",
            "Timnah",
            "Beth Shean",
        ],
        "Armenia" => &[
            "Artashat",
            "Ani",
            "Dvin",
            "Vagharshapat",
            "Tigranakert",
            "Gyumri",
            "Vanadzor",
            "Goris",
            "Kapan",
            "Sisian",
            "Ashtarak",
            "Armavir",
            "Ijevan",
            "Dilijan",
            "Meghri",
            "Yeghegnadzor",
        ],
        "Georgia" => &[
            "Tbilisi",
            "Mtskheta",
            "Kutaisi",
            "Gori",
            "Telavi",
            "Batumi",
            "Rustavi",
            "Zugdidi",
            "Akhaltsikhe",
            "Ambrolauri",
            "Ozurgeti",
            "Poti",
            "Sighnaghi",
            "Kaspi",
            "Khashuri",
            "Borjomi",
        ],
        "Timurids" => &[
            "Shahrisabz",
            "Herat",
            "Balkh",
            "Andijan",
            "Kokand",
            "Margilan",
            "Urgench",
            "Ferghana",
            "Tirmidh",
            "Qarshi",
            "Guzar",
            "Baysun",
            "Denau",
            "Jizzakh",
            "Zaamin",
            "Kattaqorgon",
        ],
        "Kazakh" => &[
            "Turkistan",
            "Taraz",
            "Otrar",
            "Sygnak",
            "Sauran",
            "Semey",
            "Karagandy",
            "Pavlodar",
            "Kokshetau",
            "Atbasar",
            "Ulytau",
            "Zhezkazgan",
            "Balkhash",
            "Ayagoz",
            "Zaysan",
            "Arkalyk",
        ],
        "Bactria" => &[
            "Bactra",
            "Ai-Khanoum",
            "Drapsaka",
            "Aornos",
            "Kapisa",
            "Bagram",
            "Kunduz",
            "Taloqan",
            "Shibarghan",
            "Maimana",
            "Andkhoy",
            "Samangan",
            "Pul-i-Khumri",
            "Baghlan",
            "Faizabad",
            "Ishkashim",
        ],
        "Ethiopia" => &[
            "Addis Ababa",
            "Gondar",
            "Lalibela",
            "Aksum",
            "Harar",
            "Dire Dawa",
            "Bahir Dar",
            "Mekele",
            "Jimma",
            "Dessie",
            "Adama",
            "Debre Markos",
            "Awasa",
            "Arba Minch",
            "Nekemte",
            "Ambo",
        ],
        "Axum" => &[
            "Axum",
            "Adulis",
            "Matara",
            "Yeha",
            "Qohaito",
            "Keskese",
            "Tekonda",
            "Hawulti",
            "Debarwa",
            "Senafe",
            "Adigrat",
            "Adwa",
            "Shire",
            "Inticho",
            "Edaga Hamus",
            "Rama",
        ],
        "Morocco" => &[
            "Marrakesh",
            "Fes",
            "Meknes",
            "Rabat",
            "Sale",
            "Taza",
            "Sijilmasa",
            "Agadir",
            "Ouarzazate",
            "Beni Mellal",
            "Khouribga",
            "Settat",
            "Safi",
            "Essaouira",
            "Ifrane",
            "Errachidia",
        ],
        "Numidia" => &[
            "Cirta",
            "Hippo Regius",
            "Thugga",
            "Zama",
            "Sicca",
            "Thagaste",
            "Madauros",
            "Calama",
            "Theveste",
            "Lambaesis",
            "Timgad",
            "Setif",
            "Tipasa",
            "Icosium",
            "Rusicade",
            "Milev",
        ],
        "Songhai" => &[
            "Kukiya",
            "Tendirma",
            "Bamba",
            "Hombori",
            "Kabara",
            "Ansongo",
            "Menaka",
            "Douentza",
            "Niafunke",
            "Goundam",
            "Dire",
            "Bourem",
            "Tillaberi",
            "Ayorou",
            "Tera",
            "Say",
        ],
        "Ghana" => &[
            "Koumbi Saleh",
            "Aoudaghost",
            "Tegdaoust",
            "Nema",
            "Tichitt",
            "Oualata",
            "Kiffa",
            "Ayoun",
            "Timbedra",
            "Bassikounou",
            "Kobenni",
            "Tamchakett",
            "Boumdeid",
            "Moudjeria",
            "Sani",
            "Rosso",
        ],
        "Benin" => &[
            "Benin City",
            "Ughoton",
            "Sabongida",
            "Ekpoma",
            "Uromi",
            "Irrua",
            "Auchi",
            "Igarra",
            "Okada",
            "Udo",
            "Ehor",
            "Iyanomo",
            "Ologbo",
            "Urhonigbe",
            "Abudu",
            "Agbor",
        ],
        "Ashanti" => &[
            "Kumasi",
            "Bekwai",
            "Mampong",
            "Ejisu",
            "Obuasi",
            "Konongo",
            "Offinso",
            "Agona",
            "Juaben",
            "Nkawie",
            "Tepa",
            "Bantama",
            "Asokwa",
            "Effiduase",
            "Kuntanase",
            "Adansi",
        ],
        "Swahili" => &[
            "Kilwa",
            "Mombasa",
            "Malindi",
            "Lamu",
            "Pate",
            "Gedi",
            "Sofala",
            "Songo Mnara",
            "Pemba",
            "Bagamoyo",
            "Tanga",
            "Mafia",
            "Comoro",
            "Vumba",
            "Shanga",
            "Manda",
        ],
        "Great Zimbabwe" => &[
            "Zimbabwe",
            "Khami",
            "Mapungubwe",
            "Naletale",
            "Danangombe",
            "Chumnungwa",
            "Ziwa",
            "Nyanga",
            "Manyikeni",
            "Tsindi",
            "Matendere",
            "Bumbusi",
            "Lekkerwater",
            "Chipadze",
            "Mtoko",
            "Chibvumani",
        ],
        "Buganda" => &[
            "Mengo",
            "Entebbe",
            "Mubende",
            "Masaka",
            "Mityana",
            "Bulemeezi",
            "Kyaggwe",
            "Buddu",
            "Singo",
            "Gomba",
            "Butambala",
            "Mawokota",
            "Busiro",
            "Kyadondo",
            "Bugerere",
            "Buvuma",
        ],
        "Oyo" => &[
            "Oyo-Ile",
            "Ibadan",
            "Ogbomoso",
            "Iseyin",
            "Saki",
            "Ede",
            "Ilorin",
            "Osogbo",
            "Iwo",
            "Ikirun",
            "Ejigbo",
            "Igboho",
            "Kishi",
            "Igbeti",
            "Fiditi",
            "Awe",
        ],
        "Tuareg" => &[
            "Agadez",
            "Tamanrasset",
            "Ghat",
            "Djanet",
            "Iferouane",
            "Arlit",
            "Bilma",
            "In Salah",
            "Timia",
            "Abalak",
            "Tchirozerine",
            "Ingall",
            "Assamakka",
            "Tabelot",
            "Dirkou",
            "Fachi",
        ],
        "Madagascar" => &[
            "Ambohimanga",
            "Fianarantsoa",
            "Toamasina",
            "Antsirabe",
            "Mahajanga",
            "Toliara",
            "Antsiranana",
            "Ambatondrazaka",
            "Morondava",
            "Manakara",
            "Sambava",
            "Farafangana",
            "Maintirano",
            "Ihosy",
            "Betroka",
            "Moramanga",
        ],
        "India" => &[
            "Pataliputra",
            "Varanasi",
            "Ujjain",
            "Taxila",
            "Kaushambi",
            "Vidisha",
            "Mathura",
            "Sravasti",
            "Rajagriha",
            "Champa",
            "Kanchipuram",
            "Indraprastha",
            "Vaishali",
            "Kausambi",
            "Sarnath",
            "Nalanda",
        ],
        "Japan" => &[
            "Kyoto",
            "Nara",
            "Osaka",
            "Kamakura",
            "Edo",
            "Nagoya",
            "Hakata",
            "Sakai",
            "Kanazawa",
            "Sendai",
            "Hiroshima",
            "Kagoshima",
            "Nagasaki",
            "Matsuyama",
            "Nikko",
            "Himeji",
        ],
        "Mongolia" => &[
            "Karakorum",
            "Avarga",
            "Ulaanbaatar",
            "Kharkhorin",
            "Erdenet",
            "Choibalsan",
            "Hovd",
            "Moron",
            "Dalanzadgad",
            "Bayankhongor",
            "Altai",
            "Tsetserleg",
            "Arvaikheer",
            "Baruun-Urt",
            "Ondorkhaan",
            "Sainshand",
        ],
        "Tibet" => &[
            "Lhasa",
            "Shigatse",
            "Gyantse",
            "Yarlung",
            "Samye",
            "Chamdo",
            "Nagchu",
            "Nyingchi",
            "Sakya",
            "Tsetang",
            "Zhongba",
            "Purang",
            "Gartok",
            "Rutog",
            "Dingri",
            "Lhatse",
        ],
        "Nepal" => &[
            "Kathmandu",
            "Bhaktapur",
            "Patan",
            "Gorkha",
            "Pokhara",
            "Janakpur",
            "Lumbini",
            "Palpa",
            "Dhankuta",
            "Ilam",
            "Butwal",
            "Nepalgunj",
            "Dang",
            "Jumla",
            "Bandipur",
            "Dolakha",
        ],
        "Kalinga" => &[
            "Tosali",
            "Dhauli",
            "Udayagiri",
            "Sisupalgarh",
            "Kalinganagara",
            "Jajpur",
            "Puri",
            "Konark",
            "Cuttack",
            "Bhubaneswar",
            "Balasore",
            "Ganjam",
            "Berhampur",
            "Sambalpur",
            "Bolangir",
            "Koraput",
        ],
        "Chola" => &[
            "Thanjavur",
            "Gangaikonda",
            "Uraiyur",
            "Kaveripattinam",
            "Madurai",
            "Tiruchirapalli",
            "Nagapattinam",
            "Kumbakonam",
            "Chidambaram",
            "Srirangam",
            "Tirunelveli",
            "Vellore",
            "Salem",
            "Karur",
            "Erode",
            "Dindigul",
        ],
        "Bengal" => &[
            "Gauda",
            "Pundravardhana",
            "Vikrampur",
            "Sonargaon",
            "Dhaka",
            "Murshidabad",
            "Rajshahi",
            "Bogra",
            "Comilla",
            "Barisal",
            "Khulna",
            "Rangpur",
            "Jessore",
            "Faridpur",
            "Mymensingh",
            "Pabna",
        ],
        "Maratha" => &[
            "Raigad",
            "Pune",
            "Satara",
            "Kolhapur",
            "Nashik",
            "Ahmednagar",
            "Sinhagad",
            "Panhala",
            "Pratapgad",
            "Torna",
            "Rajgad",
            "Shivneri",
            "Vijaydurg",
            "Sindhudurg",
            "Jinji",
            "Thanjavur Fort",
        ],
        "Khmer" => &[
            "Angkor",
            "Hariharalaya",
            "Koh Ker",
            "Sambor Prei Kuk",
            "Banteay Chhmar",
            "Battambang",
            "Preah Khan",
            "Beng Mealea",
            "Phnom Penh",
            "Kampong Thom",
            "Siem Reap",
            "Kratie",
            "Pursat",
            "Takeo",
            "Kampot",
            "Stung Treng",
        ],
        "Siam" => &[
            "Sukhothai",
            "Ayutthaya",
            "Si Satchanalai",
            "Lopburi",
            "Phitsanulok",
            "Kamphaeng Phet",
            "Nakhon Si Thammarat",
            "Chiang Mai",
            "Lampang",
            "Phetchaburi",
            "Ratchaburi",
            "Suphanburi",
            "Uttaradit",
            "Tak",
            "Phichit",
            "Nan",
        ],
        "Burma" => &[
            "Bagan",
            "Ava",
            "Sagaing",
            "Pegu",
            "Mandalay",
            "Prome",
            "Toungoo",
            "Amarapura",
            "Shwebo",
            "Myinsaing",
            "Pinya",
            "Martaban",
            "Bassein",
            "Magwe",
            "Meiktila",
            "Monywa",
        ],
        "Majapahit" => &[
            "Trowulan",
            "Kediri",
            "Singhasari",
            "Tuban",
            "Gresik",
            "Surabaya",
            "Malang",
            "Blitar",
            "Madiun",
            "Jepara",
            "Demak",
            "Semarang",
            "Banten",
            "Cirebon",
            "Sunda Kelapa",
            "Pasuruan",
        ],
        "Champa" => &[
            "Vijaya",
            "Indrapura",
            "Simhapura",
            "Panduranga",
            "Kauthara",
            "Amaravati",
            "Virapura",
            "Rajapura",
            "Phan Rang",
            "Tra Kieu",
            "My Son",
            "Tuy Hoa",
            "Hoi An",
            "Thu Bon",
            "Quang Ngai",
            "Cam Ranh",
        ],
        "America" => &[
            "Washington",
            "Philadelphia",
            "Boston",
            "Baltimore",
            "Charleston",
            "Richmond",
            "Albany",
            "Pittsburgh",
            "Cincinnati",
            "Saint Louis",
            "Detroit",
            "Chicago",
            "Denver",
            "Portland",
            "Sacramento",
            "Santa Fe",
        ],
        "Canada" => &[
            "Ottawa",
            "Quebec",
            "Montreal",
            "Toronto",
            "Halifax",
            "Winnipeg",
            "Victoria",
            "Kingston",
            "Hamilton",
            "Regina",
            "Calgary",
            "Edmonton",
            "Saskatoon",
            "Fredericton",
            "Charlottetown",
            "Thunder Bay",
        ],
        "Pueblo" => &[
            "Oraibi",
            "Walpi",
            "Sky City",
            "Kuaua",
            "Picuris",
            "Nambe",
            "Tesuque",
            "Cochiti",
            "Santo Domingo",
            "San Felipe",
            "Sandia",
            "Isleta",
            "Laguna",
            "Jemez",
            "Pecos",
            "Galisteo",
        ],
        "Comanche" => &[
            "Quahada",
            "Penateka",
            "Nokoni",
            "Yamparika",
            "Kotsoteka",
            "Tanima",
            "Palo Duro",
            "Llano Estacado",
            "Adobe Walls",
            "Medicine Lodge",
            "Cache Creek",
            "Elk Creek",
            "Antelope Hills",
            "Tule Canyon",
            "Blanco Canyon",
            "Wichita Mountains",
        ],
        "Sioux" => &[
            "Paha Sapa",
            "Bdote",
            "Mnisota",
            "Wakpa Sica",
            "Inyan Kara",
            "Mato Tipila",
            "Hunkpapa",
            "Oglala",
            "Sicangu",
            "Minneconjou",
            "Itazipco",
            "Sihasapa",
            "Oohenumpa",
            "Yankton",
            "Wahpeton",
            "Sisseton",
        ],
        "Inca" => &[
            "Cusco",
            "Ollantaytambo",
            "Pisac",
            "Vilcabamba",
            "Tiwanaku",
            "Cajamarca",
            "Huanuco",
            "Vitcos",
            "Sacsayhuaman",
            "Chinchero",
            "Andahuaylas",
            "Ayacucho",
            "Arequipa",
            "Puno",
            "Abancay",
            "Urubamba",
        ],
        "Muisca" => &[
            "Bacata",
            "Hunza",
            "Sogamoso",
            "Tunja",
            "Zipaquira",
            "Nemocon",
            "Chia",
            "Guatavita",
            "Ubate",
            "Duitama",
            "Paipa",
            "Ramiriqui",
            "Turmeque",
            "Sachica",
            "Chiquinquira",
            "Muzo",
        ],
        "Mapuche" => &[
            "Temuco",
            "Villarrica",
            "Purén",
            "Arauco",
            "Cañete",
            "Tirua",
            "Curacautin",
            "Lonquimay",
            "Nueva Imperial",
            "Carahue",
            "Pitrufquen",
            "Loncoche",
            "Angol",
            "Traiguen",
            "Collipulli",
            "Galvarino",
        ],
        "Argentina" => &[
            "Buenos Aires",
            "Tucuman",
            "Salta",
            "Mendoza",
            "Rosario",
            "La Plata",
            "Corrientes",
            "Parana",
            "San Juan",
            "La Rioja",
            "Catamarca",
            "Jujuy",
            "Bahia Blanca",
            "Neuquen",
            "Santiago del Estero",
            "Formosa",
        ],
        "Australia" => &[
            "Canberra",
            "Sydney",
            "Melbourne",
            "Brisbane",
            "Fremantle",
            "Adelaide",
            "Hobart",
            "Darwin",
            "Wollongong",
            "Ballarat",
            "Bendigo",
            "Toowoomba",
            "Geelong",
            "Kalgoorlie",
            "Broken Hill",
            "Alice Springs",
        ],
        "Maori" => &[
            "Waitangi",
            "Rotorua",
            "Tauranga",
            "Whangarei",
            "Kaitaia",
            "Gisborne",
            "Napier",
            "Taupo",
            "Wanganui",
            "Hastings",
            "Palmerston",
            "Masterton",
            "Whakatane",
            "Otaki",
            "Opotiki",
            "Kawhia",
        ],
        "Babylon" => &[
            "Babylon",
            "Ur",
            "Uruk",
            "Sippar",
            "Nippur",
            "Borsippa",
            "Kish",
            "Lagash",
            "Adab",
            "Akkad",
            "Dur-Kurigalzu",
            "Isin",
            "Larsa",
            "Umma",
            "Shuruppak",
            "Eridu",
        ],
        "Cree" => &[
            "Mikisiw-Wacihk",
            "Mistawasis",
            "Okanese",
            "Peepeekisis",
            "Sakimay",
            "Cowessess",
            "Kahkewistahaw",
            "Star Blanket",
            "Muskowekwan",
            "Pasqua",
            "George Gordon",
            "Day Star",
            "Beardy's",
            "Little Pine",
            "Sweetgrass",
            "Thunderchild",
        ],
        "Gran Colombia" => &[
            "Bogota",
            "Caracas",
            "Quito",
            "Panama City",
            "Guayaquil",
            "Cali",
            "Medellin",
            "Cartagena",
            "Cucuta",
            "Bucaramanga",
            "Maracaibo",
            "Barquisimeto",
            "Valencia",
            "Santa Marta",
            "Popayan",
            "Tunja",
        ],
        "Indonesia" => &[
            "Jakarta",
            "Surabaya",
            "Medan",
            "Makassar",
            "Palembang",
            "Bandung",
            "Banjarmasin",
            "Denpasar",
            "Yogyakarta",
            "Semarang",
            "Ternate",
            "Tidore",
            "Malang",
            "Padang",
            "Manado",
            "Kupang",
        ],
        "Macedon" => &[
            "Pella",
            "Aigai",
            "Amphipolis",
            "Dion",
            "Mygdonia",
            "Cassandreia",
            "Thessalonica",
            "Philippi",
            "Heraclea Lyncestis",
            "Stobi",
            "Edessa",
            "Beroea",
            "Olynthus",
            "Potidaea",
            "Methone",
            "Eion",
        ],
        _ => &[],
    }
}
