//! Every empire wears a Civilization VI jersey, and keeps wearing it.
//!
//! `tools/civ6_player_colors.py` reads the colours out of the shipped game and
//! writes them to two places: `data/civ6_player_colors.json` (the audit trail,
//! naming the leader each pair came from) and the generated region of
//! `web/index.html` (what actually paints the map). Only the first of those is
//! reviewable by eye, so this compares them, and neither needs Civ 6 installed
//! to check -- which is the point, since CI has no game.
//!
//! What it defends, in the order the failures actually happen:
//!
//! * A civilization added to `data/civs.json` without a jersey falls back to a
//!   generic colour, and duplicates another empire's border on the map. That is
//!   invisible until two empires meet.
//! * A hand-edit to the generated region drifts from the game's values, and the
//!   next `--write` silently reverts it.
//! * An off-palette colour looks fine alone and wrong beside the other 104.
//! * A jersey whose two halves are perceptually too close cannot draw a two-tone
//!   frontier at all: both lanes read as one band, so the border stops
//!   distinguishing its owner.
//!
//! That last one is measured as CIE76 ΔE in Lab, **not** as WCAG luminance
//! contrast, because Civ 6 separates the halves of a jersey by hue rather than
//! lightness. Its own shipped pairs go down to 1.13:1 in luminance -- Menelik's
//! Ethiopia is gold on a green of nearly identical lightness -- so a luminance
//! threshold high enough to be meaningful would reject the game's real colours,
//! which are the colours this whole change exists to adopt. In ΔE the game is
//! consistent: its 200 pairs bottom out at 26.5, and the 219 authored from its
//! palette bottom out at 26.3, so 25 is the floor both sides already clear.

use std::collections::{BTreeMap, BTreeSet};

const INDEX: &str = include_str!("../web/index.html");
const COLORS_JSON: &str = include_str!("../data/civ6_player_colors.json");
const CIVS_JSON: &str = include_str!("../data/civs.json");

const BEGIN: &str = "// >>> generated by tools/civ6_player_colors.py";
const END: &str = "// <<< generated by tools/civ6_player_colors.py";

/// The generated region, so a stray `const PCOLORS` elsewhere cannot satisfy
/// these tests by accident.
fn generated_region() -> &'static str {
    let start = INDEX.find(BEGIN).expect("generated jersey region is present");
    let end = INDEX[start..].find(END).expect("generated region is closed") + start;
    &INDEX[start..end]
}

fn hexes(list: &str) -> Vec<String> {
    let mut out = Vec::new();
    let bytes = list.as_bytes();
    for (at, _) in list.match_indices('#') {
        let hex = &list[at + 1..];
        if hex.len() >= 6 && hex.as_bytes()[..6].iter().all(u8::is_ascii_hexdigit) {
            // Guard against a longer token that merely starts with six hex
            // digits, which would silently truncate rather than fail.
            let next = bytes.get(at + 7).copied().unwrap_or(b'"');
            assert!(
                !next.is_ascii_hexdigit(),
                "colour at byte {at} is longer than #rrggbb"
            );
            out.push(format!("#{}", &hex[..6].to_ascii_lowercase()));
        }
    }
    out
}

fn js_array(region: &str, name: &str) -> Vec<String> {
    let needle = format!("const {name} = [");
    let start = region
        .find(&needle)
        .unwrap_or_else(|| panic!("{name} is declared in the generated region"))
        + needle.len();
    let end = region[start..]
        .find("];")
        .unwrap_or_else(|| panic!("{name} is closed")) + start;
    hexes(&region[start..end])
}

/// `CIV6_JERSEYS`, in declaration order. Lookup is by name so the order carries
/// no meaning at runtime; it is kept only so a regenerated table diffs cleanly
/// against the roster it was generated from.
fn jersey_table() -> Vec<(String, Vec<[String; 2]>)> {
    let region = generated_region();
    let start = region
        .find("const CIV6_JERSEYS = {")
        .expect("CIV6_JERSEYS is declared in the generated region");
    let body = &region[start..];
    let body = &body[..body.find("\n};").expect("CIV6_JERSEYS is closed")];

    let mut out = Vec::new();
    for line in body.lines().skip(1) {
        let line = line.trim();
        if line.is_empty() || line.starts_with("//") {
            continue;
        }
        let (key, rest) = line.split_once(':').expect("a jersey line is `name: [...]`");
        let name = key.trim().trim_matches('"').to_string();
        let colours = hexes(rest);
        assert_eq!(
            colours.len() % 2,
            0,
            "{name} has an odd number of colours, so some pair is half a jersey"
        );
        let pairs = colours
            .chunks(2)
            .map(|pair| [pair[0].clone(), pair[1].clone()])
            .collect();
        out.push((name, pairs));
    }
    out
}

fn roster() -> Vec<String> {
    let civs: serde_json::Value = serde_json::from_str(CIVS_JSON).expect("data/civs.json parses");
    civs.as_object()
        .expect("data/civs.json is an object keyed by civilization")
        .keys()
        .cloned()
        .collect()
}

/// sRGB to CIE L\*a\*b\*, D65 white.
fn lab(hex: &str) -> [f64; 3] {
    let linear = |at: usize| {
        let raw = u8::from_str_radix(&hex[at..at + 2], 16).expect("hex channel") as f64 / 255.0;
        if raw <= 0.04045 {
            raw / 12.92
        } else {
            ((raw + 0.055) / 1.055).powf(2.4)
        }
    };
    let (r, g, b) = (linear(1), linear(3), linear(5));
    let x = (0.4124 * r + 0.3576 * g + 0.1805 * b) / 0.95047;
    let y = 0.2126 * r + 0.7152 * g + 0.0722 * b;
    let z = (0.0193 * r + 0.1192 * g + 0.9505 * b) / 1.08883;
    let f = |t: f64| {
        if t > 216.0 / 24389.0 {
            t.cbrt()
        } else {
            (841.0 / 108.0) * t + 4.0 / 29.0
        }
    };
    let (fx, fy, fz) = (f(x), f(y), f(z));
    [116.0 * fy - 16.0, 500.0 * (fx - fy), 200.0 * (fy - fz)]
}

/// CIE76 ΔE: how far apart two colours look, counting hue and chroma as well as
/// lightness. See the module comment for why this and not WCAG contrast.
fn delta_e(a: &str, b: &str) -> f64 {
    let (x, y) = (lab(a), lab(b));
    ((x[0] - y[0]).powi(2) + (x[1] - y[1]).powi(2) + (x[2] - y[2]).powi(2)).sqrt()
}

#[test]
fn every_civilization_in_the_roster_has_exactly_one_jersey() {
    let table = jersey_table();
    let mut named: BTreeSet<String> = BTreeSet::new();
    for (name, _) in &table {
        assert!(
            named.insert(name.clone()),
            "{name} appears twice in the jersey table; the later wins silently"
        );
    }
    let roster: BTreeSet<String> = roster().into_iter().collect();

    let unjerseyed: Vec<&String> = roster.difference(&named).collect();
    assert!(
        unjerseyed.is_empty(),
        "these civilizations would fall back to a generic colour: {unjerseyed:?} -- \
         regenerate with tools/civ6_player_colors.py --write --json"
    );
    let unrostered: Vec<&String> = named.difference(&roster).collect();
    assert!(
        unrostered.is_empty(),
        "these jerseys name a civilization not in data/civs.json: {unrostered:?}"
    );

    for (name, pairs) in &table {
        assert!(
            !pairs.is_empty(),
            "{name} has a jersey entry with no colour pairs in it"
        );
    }
}

#[test]
fn the_generated_region_matches_the_checked_in_civ6_extract() {
    let extract: serde_json::Value =
        serde_json::from_str(COLORS_JSON).expect("data/civ6_player_colors.json parses");
    let jerseys = extract["jerseys"]
        .as_object()
        .expect("the extract carries a jersey per civilization");

    for (name, pairs) in jersey_table() {
        let entry = jerseys
            .get(&name)
            .unwrap_or_else(|| panic!("{name} is missing from data/civ6_player_colors.json"));
        let expected: Vec<[String; 2]> = entry["pairs"]
            .as_array()
            .expect("pairs is an array")
            .iter()
            .map(|pair| {
                let pair = pair.as_array().expect("a pair is [primary, secondary]");
                [
                    pair[0].as_str().expect("primary is a string").to_string(),
                    pair[1].as_str().expect("secondary is a string").to_string(),
                ]
            })
            .collect();
        assert_eq!(
            pairs, expected,
            "{name} in web/index.html disagrees with data/civ6_player_colors.json; \
             the JSON is the extract from the game, so regenerate rather than hand-editing"
        );
    }
}

#[test]
fn every_jersey_colour_is_a_civ6_palette_colour() {
    let extract: serde_json::Value =
        serde_json::from_str(COLORS_JSON).expect("data/civ6_player_colors.json parses");
    let palette: BTreeMap<String, String> = extract["palette"]
        .as_object()
        .expect("the extract carries the palette it drew from")
        .iter()
        .map(|(token, value)| {
            (
                value.as_str().expect("a palette colour is a string").to_string(),
                token.clone(),
            )
        })
        .collect();
    assert_eq!(
        palette.len(),
        28,
        "Civ 6 ships 28 standard player colours; a different count means the extract \
         picked up something other than PlayerStandardColors"
    );

    let region = generated_region();
    let mut checked = 0;
    for (name, pairs) in jersey_table() {
        for pair in &pairs {
            for colour in pair {
                assert!(
                    palette.contains_key(colour),
                    "{name} wears {colour}, which is not in Civ 6's player palette"
                );
                checked += 1;
            }
        }
    }
    for (index, colour) in js_array(region, "PCOLORS")
        .into_iter()
        .chain(js_array(region, "PCOLORS2"))
        .enumerate()
    {
        assert!(
            palette.contains_key(&colour),
            "fallback colour {index} is {colour}, which is not in Civ 6's player palette"
        );
        checked += 1;
    }
    assert!(checked > 800, "only {checked} colours checked; the parse found too little");
}

#[test]
fn the_generic_fallback_gives_every_player_id_its_own_primary() {
    let region = generated_region();
    let primaries = js_array(region, "PCOLORS");
    let partners = js_array(region, "PCOLORS2");

    assert_eq!(
        primaries.len(),
        partners.len(),
        "PCOLORS and PCOLORS2 are one jersey read from two arrays, so they must align"
    );
    assert!(
        primaries.len() >= 12,
        "the fallback must cover a full lobby, got {}",
        primaries.len()
    );
    let distinct: BTreeSet<&String> = primaries.iter().collect();
    assert_eq!(
        distinct.len(),
        primaries.len(),
        "a repeated primary hands two seats the same territory colour: {:?}",
        primaries
    );
}

/// A two-tone frontier needs its two lanes to look different, or the border
/// collapses into one band and stops naming its owner.
#[test]
fn every_jersey_pair_can_draw_a_two_tone_border() {
    const FLOOR: f64 = 25.0;
    let mut worst: Option<(f64, String, [String; 2])> = None;
    for (name, pairs) in jersey_table() {
        for pair in pairs {
            let separation = delta_e(&pair[0], &pair[1]);
            if worst.as_ref().is_none_or(|(low, _, _)| separation < *low) {
                worst = Some((separation, name.clone(), pair.clone()));
            }
            assert!(
                separation >= FLOOR,
                "{name} pairs {} with {} at ΔE {separation:.1} -- too close to draw two lanes",
                pair[0],
                pair[1]
            );
        }
    }
    let (separation, name, pair) = worst.expect("there are jerseys to check");
    println!(
        "tightest jersey: {name} {}/{} at ΔE {separation:.1} (floor {FLOOR})",
        pair[0], pair[1]
    );
}
