#!/usr/bin/env python3
"""Sim-vs-live divergence replay: score the engine's next turn against the game's.

Drives ``target/release/live_divergence`` (``src/bin/live_divergence.rs``) over a
recorded live seat's ``events.jsonl``, aggregates the (live, sim) pairs it
emits per subsystem — mean absolute error, median, the five worst turns,
coverage — and writes:

* ``docs/fidelity/<run>.md``        the generated per-run report
* ``docs/fidelity/scoreboard.json`` one entry per run, newest first
* ``docs/fidelity/SCOREBOARD.md``   one row per run per subsystem, newest first
* ``docs/fidelity/waivers.json``    per-subsystem MAE thresholds

The comparison is PROJECTION-ONLY: the live record carries order COUNTS, not
orders with targets, so nothing is replayed; the engine evolves the mirrored
frame at ``t`` by one passive turn and is scored against the export at ``t+1``.
The bin's header says why; every report repeats it.

Thresholds seed themselves from the first three runs a subsystem is measured on
(the largest of the three MAEs) and then freeze; ``--check`` fails when a
subsystem's MAE exceeds its threshold. This is a local ratchet over the
committed scoreboard — the runs themselves live only on the Civilization VI
seat, so a runner elsewhere can only check the scoreboard, never re-measure.

Usage::

    python3 tools/live_divergence.py <run_dir|events.jsonl> [--turns a-b]
        [--out docs/fidelity/<run>.md] [--json] [--bin PATH]
        [--fidelity-dir docs/fidelity] [--no-scoreboard]
        [--check] [--waivers docs/fidelity/waivers.json]
    python3 tools/live_divergence.py --check [--waivers docs/fidelity/waivers.json]
        [--scoreboard docs/fidelity/scoreboard.json]

The second form checks the newest scoreboard row of every subsystem against
its threshold and exits 1 on a breach.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import json
import os
import statistics
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
FIDELITY_DIR = REPO / "docs" / "fidelity"
SEED_RUNS = 3
WORST = 5
GENERATED = "<!-- generated by tools/live_divergence.py; do not edit by hand -->"

SUBSYSTEM_ORDER = [
    "city_science", "city_culture", "city_gold", "city_faith", "city_food",
    "city_production", "empire_gold_delta", "empire_faith_delta",
    "empire_favor_delta", "city_loyalty", "city_religion", "tourism",
    "combat_damage", "deal_outcome",
]


# ----------------------------------------------------------------- arithmetic

def summarize_subsystem(name: str, sub: dict, comparable_turns: int) -> dict:
    """Reduce one subsystem's pairs to MAE, median, worst turns and coverage.

    Coverage is the share of comparable turns (frame at t AND t+1) on which at
    least one pair exists. A subsystem nothing exported has n=0, coverage 0 and
    no MAE — never an MAE of 0.
    """
    pairs = sub.get("pairs", [])
    errors = [abs(float(p["live"]) - float(p["sim"])) for p in pairs]
    turns = sorted({int(p["turn"]) for p in pairs})
    worst_by_turn: dict[int, dict] = {}
    for pair, err in zip(pairs, errors):
        turn = int(pair["turn"])
        if turn not in worst_by_turn or err > worst_by_turn[turn]["abs"]:
            worst_by_turn[turn] = {
                "turn": turn, "key": pair["key"], "live": pair["live"],
                "sim": pair["sim"], "abs": err,
            }
    worst = sorted(worst_by_turn.values(), key=lambda w: (-w["abs"], w["turn"]))[:WORST]
    return {
        "name": name,
        "unit": sub.get("unit", ""),
        "note": sub.get("note", ""),
        "n": len(pairs),
        "turns": len(turns),
        "coverage": (len(turns) / comparable_turns) if comparable_turns else 0.0,
        "mae": (sum(errors) / len(errors)) if errors else None,
        "median": statistics.median(errors) if errors else None,
        "worst": worst,
    }


def summarize(report: dict, processed_at: str | None = None, source_commit: str = "") -> dict:
    comparable = int(report.get("comparable_turns", 0))
    subsystems = {}
    names = list(SUBSYSTEM_ORDER) + sorted(set(report.get("subsystems", {})) - set(SUBSYSTEM_ORDER))
    for name in names:
        sub = report.get("subsystems", {}).get(name)
        if sub is None:
            continue
        subsystems[name] = summarize_subsystem(name, sub, comparable)
    frame_turns = report.get("frame_turns", [])
    return {
        "run": report.get("run", ""),
        "events": report.get("events", ""),
        "mode": report.get("mode", "projection"),
        "processed_at": processed_at or _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "source_commit": source_commit,
        "frames": int(report.get("frames", 0)),
        "first_turn": min(frame_turns) if frame_turns else None,
        "last_turn": max(frame_turns) if frame_turns else None,
        "comparable_turns": comparable,
        "compared_turns": int(report.get("compared_turns", 0)),
        "skipped": list(report.get("skipped", [])),
        "subsystems": subsystems,
    }


# -------------------------------------------------------------------- report

def _num(value, digits: int = 3) -> str:
    if value is None:
        return "-"
    return f"{value:.{digits}f}"


def _pct(value: float) -> str:
    return f"{100.0 * value:.0f}%"


def render_run_report(summary: dict, thresholds: dict | None = None) -> str:
    thresholds = thresholds or {}
    lines = [
        GENERATED,
        f"# Divergence replay: `{summary['run']}`",
        "",
        f"Processed {summary['processed_at']}"
        + (f" at `{summary['source_commit'][:12]}`" if summary.get("source_commit") else "")
        + f" from `{summary['events']}`.",
        "",
        f"**Mode: {summary['mode']}.** The live record carries order counts, not "
        "orders with targets, so nothing is replayed: the engine mirrors the frame "
        "at `t`, plays one passive turn (every seat ends its turn, no order is "
        "issued) and is scored against the export at `t+1`.",
        "",
        f"Frames: {summary['frames']} (turns {summary['first_turn']}–{summary['last_turn']}); "
        f"comparable turns (frame at t and t+1): {summary['comparable_turns']}; "
        f"compared: {summary['compared_turns']}.",
    ]
    if summary.get("skipped"):
        lines += ["", "Skipped: " + "; ".join(summary["skipped"])]
    lines += [
        "",
        "| Subsystem | Unit | Pairs | Turns covered | Coverage | MAE | Median | Threshold |",
        "|---|---|---:|---:|---:|---:|---:|---:|",
    ]
    for name, sub in summary["subsystems"].items():
        threshold = thresholds.get(name, {}).get("mae")
        status = "-"
        if threshold is not None and sub["mae"] is not None:
            status = f"{threshold:.3f} {'OK' if sub['mae'] <= threshold else 'BREACH'}"
        lines.append(
            f"| {name} | {sub['unit']} | {sub['n']} | {sub['turns']}/{summary['comparable_turns']} "
            f"| {_pct(sub['coverage'])} | {_num(sub['mae'])} | {_num(sub['median'])} | {status} |"
        )
    lines += ["", "## Worst turns per subsystem", ""]
    for name, sub in summary["subsystems"].items():
        lines.append(f"### {name}")
        lines.append("")
        lines.append(sub["note"])
        lines.append("")
        if not sub["worst"]:
            lines.append("No pair could be formed.")
            lines.append("")
            continue
        lines.append("| Turn | Subject | Live | Sim | Abs error |")
        lines.append("|---:|---|---:|---:|---:|")
        for w in sub["worst"]:
            lines.append(f"| {w['turn']} | {w['key']} | {_num(w['live'])} | {_num(w['sim'])} | {_num(w['abs'])} |")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_scoreboard(entries: list[dict], thresholds: dict) -> str:
    lines = [
        GENERATED,
        "# Sim-vs-live divergence scoreboard",
        "",
        "One row per run per subsystem, newest run first. MAE is the mean absolute "
        "error of the engine's one-turn passive projection against the live frame "
        "at `t+1`; coverage is the share of comparable turns with at least one pair. "
        "Thresholds come from `waivers.json` (seeded from the first three runs "
        "measured, then frozen); `python3 tools/live_divergence.py --check` fails on "
        "a breach. Per-run detail: `docs/fidelity/<run>.md`.",
        "",
        "| Run | Processed | Subsystem | Pairs | Coverage | MAE | Median | Threshold | Status |",
        "|---|---|---|---:|---:|---:|---:|---:|---|",
    ]
    for entry in entries:
        for name, sub in entry["subsystems"].items():
            threshold = thresholds.get(name, {}).get("mae")
            if sub["mae"] is None:
                status = "no pairs"
            elif threshold is None:
                status = "unwaived"
            else:
                status = "OK" if sub["mae"] <= threshold else "BREACH"
            lines.append(
                f"| [{entry['run']}]({entry['run']}.md) | {entry['processed_at'][:10]} | {name} "
                f"| {sub['n']} | {_pct(sub['coverage'])} | {_num(sub['mae'])} | {_num(sub['median'])} "
                f"| {_num(threshold)} | {status} |"
            )
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------- scoreboard

def load_json(path: Path, default):
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def upsert_scoreboard(entries: list[dict], summary: dict) -> list[dict]:
    """Replace any earlier entry for the same run; newest processed first."""
    kept = [e for e in entries if e.get("run") != summary["run"]]
    kept.append(summary)
    kept.sort(key=lambda e: (e.get("processed_at", ""), e.get("run", "")), reverse=True)
    return kept


def seed_thresholds(waivers: dict, summary: dict) -> dict:
    """Record a run into the seed set of every subsystem it measured.

    A threshold is the largest MAE of the first ``SEED_RUNS`` measured runs; once
    a subsystem has that many seeds the threshold freezes and later runs only
    get checked. A subsystem with no pairs contributes no seed.
    """
    thresholds = waivers.setdefault("thresholds", {})
    for name, sub in summary["subsystems"].items():
        if sub["mae"] is None:
            continue
        entry = thresholds.setdefault(name, {"mae": None, "seeds": [], "frozen": False})
        if entry.get("frozen"):
            continue
        seeds = [s for s in entry["seeds"] if s["run"] != summary["run"]]
        seeds.append({"run": summary["run"], "mae": sub["mae"]})
        entry["seeds"] = seeds[:SEED_RUNS]
        entry["mae"] = max(s["mae"] for s in entry["seeds"])
        entry["frozen"] = len(entry["seeds"]) >= SEED_RUNS
    waivers.setdefault("seed_runs", SEED_RUNS)
    waivers.setdefault("policy", (
        "threshold = max MAE of the first three runs measured per subsystem, then frozen; "
        "raise a threshold only with a note saying which engine change moved it"
    ))
    return waivers


def breaches(summary: dict, waivers: dict) -> list[str]:
    out = []
    for name, sub in summary["subsystems"].items():
        threshold = waivers.get("thresholds", {}).get(name, {}).get("mae")
        if threshold is None or sub["mae"] is None:
            continue
        if sub["mae"] > threshold:
            out.append(f"{summary['run']}: {name} MAE {sub['mae']:.3f} > waived {threshold:.3f}")
    return out


def newest_per_subsystem(entries: list[dict]) -> dict:
    """The newest scoreboard entry that measured each subsystem, as one pseudo-run."""
    picked: dict[str, dict] = {}
    runs: dict[str, str] = {}
    for entry in entries:  # newest first
        for name, sub in entry["subsystems"].items():
            if name not in picked and sub["mae"] is not None:
                picked[name] = sub
                runs[name] = entry["run"]
    return {"run": "scoreboard", "subsystems": picked, "runs": runs}


# ------------------------------------------------------------- FIDELITY.md

FIDELITY_DOC = REPO / "docs" / "FIDELITY.md"
DOC_BEGIN = "<!-- live-divergence:begin -->"
DOC_END = "<!-- live-divergence:end -->"


def render_fidelity_section(entries: list[dict], thresholds: dict) -> str:
    """The generated "Measured divergence" block for docs/FIDELITY.md.

    The database audit above it says whether the RULES match; this says whether
    the ENGINE's next turn matches the game's, on the newest run that measured
    each subsystem. The scoreboard carries every run.
    """
    pseudo = newest_per_subsystem(entries)
    lines = [
        DOC_BEGIN,
        "## Measured divergence: the engine's next turn against the game's",
        "",
        "Generated by `tools/live_divergence.py`; do not edit by hand. For every "
        "turn `t` of a recorded live seat with a frame at `t` and `t+1`, the engine "
        "mirrors the frame at `t`, plays one passive turn and is scored against the "
        "export at `t+1`. Projection-only: the live record carries order counts, not "
        "orders with targets, so nothing is replayed. Full table, every run: "
        "[docs/fidelity/SCOREBOARD.md](fidelity/SCOREBOARD.md); thresholds: "
        "[docs/fidelity/waivers.json](fidelity/waivers.json); "
        f"runs measured: {len(entries)}.",
        "",
        "| Subsystem | Newest run | Pairs | Coverage | MAE | Median | Threshold |",
        "|---|---|---:|---:|---:|---:|---:|",
    ]
    for name, sub in pseudo["subsystems"].items():
        run = pseudo["runs"][name]
        lines.append(
            f"| {name} | [{run}](fidelity/{run}.md) | {sub['n']} | {_pct(sub['coverage'])} "
            f"| {_num(sub['mae'])} | {_num(sub['median'])} | {_num(thresholds.get(name, {}).get('mae'))} |"
        )
    unmeasured = [name for name in SUBSYSTEM_ORDER if name not in pseudo["subsystems"]]
    if unmeasured:
        lines += ["", "No pair could be formed on any run for: " + ", ".join(f"`{n}`" for n in unmeasured)
                  + " — the export or the ledger does not carry them yet."]
    lines.append(DOC_END)
    return "\n".join(lines) + "\n"


def update_fidelity_doc(text: str, section: str) -> str:
    """Replace the marked block, or append it when the document has none."""
    begin = text.find(DOC_BEGIN)
    end = text.find(DOC_END)
    if begin == -1 or end == -1 or end < begin:
        return text.rstrip("\n") + "\n\n" + section
    end += len(DOC_END)
    if end < len(text) and text[end] == "\n":
        end += 1
    return text[:begin] + section + text[end:]


# -------------------------------------------------------------------- driver

def find_binary(explicit: str | None) -> Path:
    if explicit:
        return Path(explicit)
    candidates = []
    if os.environ.get("CARGO_TARGET_DIR"):
        candidates.append(Path(os.environ["CARGO_TARGET_DIR"]) / "release" / "live_divergence")
    candidates.append(REPO / "target" / "release" / "live_divergence")
    for path in candidates:
        if path.exists():
            return path
    print("live_divergence: building target/release/live_divergence", file=sys.stderr)
    subprocess.run(
        ["cargo", "build", "--release", "--bin", "live_divergence"],
        cwd=REPO, check=True,
    )
    for path in candidates:
        if path.exists():
            return path
    raise SystemExit("live_divergence: binary not found after build")


def run_binary(binary: Path, events: Path, turns: str | None) -> dict:
    cmd = [str(binary), str(events)]
    if turns:
        cmd += ["--turns", turns]
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        raise SystemExit(f"live_divergence: bin failed ({proc.returncode}): {proc.stderr.strip()}")
    return json.loads(proc.stdout)


def git_head() -> str:
    try:
        return subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=REPO, capture_output=True, text=True, check=True
        ).stdout.strip()
    except (subprocess.CalledProcessError, OSError):
        return ""


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("run", nargs="?", help="run directory or its events.jsonl")
    ap.add_argument("--turns", help="only compare frames in this inclusive range, e.g. 20-80")
    ap.add_argument("--out", help="report path (default docs/fidelity/<run>.md)")
    ap.add_argument("--json", action="store_true", help="print the run summary as JSON")
    ap.add_argument("--bin", help="live_divergence binary (default target/release/live_divergence)")
    ap.add_argument("--fidelity-dir", default=str(FIDELITY_DIR))
    ap.add_argument("--no-scoreboard", action="store_true", help="write only the report")
    ap.add_argument("--fidelity-doc", default=str(FIDELITY_DOC), help="FIDELITY.md carrying the generated section")
    ap.add_argument("--check", action="store_true", help="exit 1 when a subsystem's MAE exceeds its waiver")
    ap.add_argument("--waivers", help="waivers file (default <fidelity-dir>/waivers.json)")
    ap.add_argument("--scoreboard", help="scoreboard.json to check (default <fidelity-dir>/scoreboard.json)")
    args = ap.parse_args(argv)

    fidelity_dir = Path(args.fidelity_dir)
    waivers_path = Path(args.waivers) if args.waivers else fidelity_dir / "waivers.json"
    scoreboard_path = Path(args.scoreboard) if args.scoreboard else fidelity_dir / "scoreboard.json"
    waivers = load_json(waivers_path, {"thresholds": {}})

    if not args.run:
        if not args.check:
            ap.error("a run directory is required unless --check reads the scoreboard")
        entries = load_json(scoreboard_path, {"runs": []}).get("runs", [])
        pseudo = newest_per_subsystem(entries)
        failed = breaches(pseudo, waivers)
        for line in failed:
            print("BREACH " + line)
        print(f"checked {len(pseudo['subsystems'])} subsystems across {len(entries)} runs: "
              f"{len(failed)} breach(es)")
        return 1 if failed else 0

    events = Path(args.run)
    if events.is_dir():
        events = events / "events.jsonl"
    if not events.exists():
        raise SystemExit(f"live_divergence: no events.jsonl at {events}")
    report = run_binary(find_binary(args.bin), events, args.turns)
    summary = summarize(report, source_commit=git_head())

    if not args.no_scoreboard:
        seed_thresholds(waivers, summary)
    thresholds = waivers.get("thresholds", {})
    out = Path(args.out) if args.out else fidelity_dir / f"{summary['run']}.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_run_report(summary, thresholds), encoding="utf-8")

    if not args.no_scoreboard:
        board = load_json(scoreboard_path, {"runs": []})
        board["runs"] = upsert_scoreboard(board.get("runs", []), summary)
        board["generated_by"] = "tools/live_divergence.py"
        scoreboard_path.parent.mkdir(parents=True, exist_ok=True)
        scoreboard_path.write_text(json.dumps(board, indent=1, sort_keys=True) + "\n", encoding="utf-8")
        (fidelity_dir / "SCOREBOARD.md").write_text(render_scoreboard(board["runs"], thresholds), encoding="utf-8")
        waivers_path.write_text(json.dumps(waivers, indent=1, sort_keys=True) + "\n", encoding="utf-8")
        doc = Path(args.fidelity_doc)
        if doc.exists():
            doc.write_text(
                update_fidelity_doc(doc.read_text(encoding="utf-8"), render_fidelity_section(board["runs"], thresholds)),
                encoding="utf-8",
            )

    if args.json:
        print(json.dumps(summary, indent=1, sort_keys=True))
    else:
        print(f"{summary['run']}: {summary['compared_turns']}/{summary['comparable_turns']} turns compared -> {out}")
        for name, sub in summary["subsystems"].items():
            print(f"  {name:20s} n={sub['n']:5d} cov={_pct(sub['coverage']):>4s} mae={_num(sub['mae'])} median={_num(sub['median'])}")
    if args.check:
        failed = breaches(summary, waivers)
        for line in failed:
            print("BREACH " + line)
        return 1 if failed else 0
    return 0


if __name__ == "__main__":
    sys.exit(main())
