#!/usr/bin/env python3
"""The divergence queue is generated from four sources, each optional, oldest first."""

from __future__ import annotations

import json
import sys
import unittest
from pathlib import Path
from tempfile import TemporaryDirectory

sys.path.insert(0, str(Path(__file__).resolve().parent))

import fidelity_queue  # noqa: E402


def orders_block(unit_refused: int, produce_refused: int = 0) -> dict:
    return {
        "*": {"seen": 100, "applied": 100 - unit_refused - produce_refused, "refused": {}},
        "unit": {"seen": 80, "applied": 80 - unit_refused,
                 "refused": {"unit_gone": unit_refused} if unit_refused else {}},
        "produce": {"seen": 20, "applied": 20 - produce_refused,
                    "refused": {"no_params_DISTRICT_CAMPUS": produce_refused}
                    if produce_refused else {}},
    }


def write_run(runs: Path, tag: str, finished: str, orders: dict, events: list[dict] | None = None
              ) -> None:
    run = runs / tag
    run.mkdir(parents=True)
    (run / "summary.json").write_text(json.dumps(
        {"tag": tag, "finished_utc": finished, "orders": orders}))
    if events is not None:
        (run / "events.jsonl").write_text("".join(json.dumps(event) + "\n" for event in events))


class Queue(unittest.TestCase):
    def setUp(self):
        self.tmp = TemporaryDirectory()
        self.root = Path(self.tmp.name)
        self.runs = self.root / "runs"
        # Over the window: unit refused 12/240 = 5% exactly (NOT above), produce
        # refused 6/60 = 10% (above), first seen on the oldest run.
        write_run(self.runs, "civvis-1", "2026-08-20T10:00:00Z", orders_block(4, 2))
        write_run(self.runs, "civvis-2", "2026-08-21T10:00:00Z", orders_block(4, 2))
        write_run(self.runs, "civvis-3", "2026-08-22T10:00:00Z", orders_block(4, 2))
        # An older run outside a --last 3 window with a huge refusal share.
        write_run(self.runs, "civvis-0", "2026-08-10T10:00:00Z", orders_block(70))

    def tearDown(self):
        self.tmp.cleanup()

    def test_live_rows_are_above_share_and_dated_by_first_run(self):
        rows = fidelity_queue.live_rows(self.runs, 3, 0.05)
        self.assertEqual(len(rows), 1)
        row = rows[0]
        self.assertEqual(row["when"], "2026-08-20T10:00:00Z")
        self.assertEqual(row["ref"], "civvis-1")
        self.assertIn("`produce` refused `no_params_DISTRICT_CAMPUS`", row["what"])
        self.assertEqual(row["number"], "6/60 = 10.0% of the kind")
        # A lower share admits the 5% unit row; a wider window admits civvis-0's.
        self.assertEqual(len(fidelity_queue.live_rows(self.runs, 3, 0.04)), 2)
        wide = fidelity_queue.live_rows(self.runs, 4, 0.2)   # unit 82/320 = 25.6%
        self.assertEqual([r["ref"] for r in wide], ["civvis-0"])

    def test_postcondition_rows_surface_noops_with_their_own_denominator(self):
        for index, finished in enumerate(("2026-08-20T10:00:00Z", "2026-08-21T10:00:00Z")):
            write_run(
                self.runs, f"civvis-v{index}", finished, orders_block(0),
                [
                    {"kind": "order_verified", "order_kind": "produce"},
                    {"kind": "order_failed", "order_kind": "produce",
                     "reason": "producing=nothing"},
                    {"kind": "order_verified", "order_kind": "unit"},
                    # This legacy record is intentionally not attributed to a
                    # named kind and cannot create a false queue row.
                    {"kind": "order_failed", "reason": "unknown_kind"},
                ])
        rows = fidelity_queue.postcondition_rows(self.runs, 6, 0.2)
        self.assertEqual(len(rows), 1)
        row = rows[0]
        self.assertEqual(row["when"], "2026-08-20T10:00:00Z")
        self.assertEqual(row["ref"], "civvis-v0")
        self.assertIn("`produce` failed postcondition `producing=nothing`", row["what"])
        self.assertEqual(row["number"], "2/4 = 50.0% of checkable outcomes")

    def test_absent_sources_are_tolerated(self):
        text = fidelity_queue.build(
            None, last=5, share=0.05, scoreboard=self.root / "none.md",
            threshold=0.0, fidelity=self.root / "none.json")
        self.assertIn("no runs directory", text)
        self.assertIn("scoreboard: absent", text)
        self.assertIn("rules audit: absent", text)
        self.assertIn("Nothing queued.", text)

    def test_scoreboard_and_fidelity_rows_join_the_queue_oldest_first(self):
        board = self.root / "SCOREBOARD.md"
        board.write_text("\n".join([
            "<!-- generated by tools/live_divergence.py -->", "# Scoreboard", "",
            "| Run | Processed | Subsystem | Pairs | Coverage | MAE | Median | Threshold | Status |",
            "|---|---|---|---:|---:|---:|---:|---:|---|",
            "| [civvis-9](civvis-9.md) | 2026-08-15 | city_science | 10 | 100% | 1.310 | 0.1 | 0.995 | BREACH |",
            "| [civvis-9](civvis-9.md) | 2026-08-15 | city_gold | 10 | 100% | 0.020 | 0.0 | 1.139 | OK |",
            "| [civvis-9](civvis-9.md) | 2026-08-15 | tourism | 0 | 0% | - | - | - | no pairs |",
            "| [civvis-8](civvis-8.md) | 2026-08-01 | city_culture | 10 | 100% | 0.400 | 0.0 | 0.300 | BREACH |",
            "", "not a table line",
        ]))
        report = self.root / "fidelity.json"
        report.write_text(json.dumps([
            {"table": "units", "compared": 3, "waived": 1, "divergences": [
                {"table": "units", "entry": "UNIT_SLINGER", "field": "cost",
                 "ours": 35, "theirs": 40}]},
            {"table": "buildings", "compared": 1, "waived": 0, "divergences": []},
        ]))
        text = fidelity_queue.build(self.runs, last=3, share=0.05, scoreboard=board,
                                    threshold=0.1, fidelity=report)
        lines = [line for line in text.splitlines() if line.startswith("- 2") or
                 line.startswith("- undated")]
        self.assertEqual(len(lines), 4)
        self.assertIn("`city_culture`", lines[0])     # 2026-08-01, oldest
        self.assertIn("`city_science`", lines[1])     # 2026-08-15
        self.assertIn("1.310 > threshold 0.995", lines[1])
        self.assertIn("civvis-9", lines[1])
        self.assertNotIn("[civvis-9]", lines[1])      # the link is unwrapped
        self.assertIn("no_params_DISTRICT_CAMPUS", lines[2])  # 2026-08-20
        self.assertIn("UNIT_SLINGER.cost", lines[3])  # undated last
        self.assertIn("ours 35 theirs 40", lines[3])
        self.assertNotIn("city_gold", text)           # under its threshold
        self.assertNotIn("tourism", text)             # no pairs, no number
        self.assertIn("scoreboard: 2 above threshold", text)
        self.assertIn("rules audit: 1 unwaived", text)

    def test_cli_writes_the_queue(self):
        out = self.root / "QUEUE.md"
        self.assertEqual(fidelity_queue.main([
            "--runs", str(self.runs), "--last", "3", "--write", str(out),
            "--scoreboard", str(self.root / "no.md"), "--fidelity", str(self.root / "no.json")]), 0)
        self.assertIn("# Divergence queue", out.read_text())
        self.assertIn("civvis-1", out.read_text())


if __name__ == "__main__":
    unittest.main()
